//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Inputs/Playercontrols.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Playercontrols : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Playercontrols()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Playercontrols"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""72df6ec2-dd22-4830-b6d0-612f49220554"",
            ""actions"": [
                {
                    ""name"": ""TouchObjectA"",
                    ""type"": ""Value"",
                    ""id"": ""da8a7165-2cb1-435b-a558-3d1a794c2586"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchObjectB"",
                    ""type"": ""Value"",
                    ""id"": ""4069f2cd-b673-476b-a5fe-4cdee9295b42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchObjectC"",
                    ""type"": ""Value"",
                    ""id"": ""730139c9-6867-4e11-a79d-d9e56db4408d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a2b65710-911d-4cee-b5c1-e7066088201e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchObjectA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""561dce11-346b-4cc1-9b73-281704314a0a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchObjectB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34c68edb-fdb7-4dc2-a389-4b2d69daef49"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchObjectB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aeb80dd1-5703-4d2d-999a-23dd10e83c24"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchObjectC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_TouchObjectA = m_InGame.FindAction("TouchObjectA", throwIfNotFound: true);
        m_InGame_TouchObjectB = m_InGame.FindAction("TouchObjectB", throwIfNotFound: true);
        m_InGame_TouchObjectC = m_InGame.FindAction("TouchObjectC", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private IInGameActions m_InGameActionsCallbackInterface;
    private readonly InputAction m_InGame_TouchObjectA;
    private readonly InputAction m_InGame_TouchObjectB;
    private readonly InputAction m_InGame_TouchObjectC;
    public struct InGameActions
    {
        private @Playercontrols m_Wrapper;
        public InGameActions(@Playercontrols wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchObjectA => m_Wrapper.m_InGame_TouchObjectA;
        public InputAction @TouchObjectB => m_Wrapper.m_InGame_TouchObjectB;
        public InputAction @TouchObjectC => m_Wrapper.m_InGame_TouchObjectC;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void SetCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterface != null)
            {
                @TouchObjectA.started -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectA;
                @TouchObjectA.performed -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectA;
                @TouchObjectA.canceled -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectA;
                @TouchObjectB.started -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectB;
                @TouchObjectB.performed -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectB;
                @TouchObjectB.canceled -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectB;
                @TouchObjectC.started -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectC;
                @TouchObjectC.performed -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectC;
                @TouchObjectC.canceled -= m_Wrapper.m_InGameActionsCallbackInterface.OnTouchObjectC;
            }
            m_Wrapper.m_InGameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TouchObjectA.started += instance.OnTouchObjectA;
                @TouchObjectA.performed += instance.OnTouchObjectA;
                @TouchObjectA.canceled += instance.OnTouchObjectA;
                @TouchObjectB.started += instance.OnTouchObjectB;
                @TouchObjectB.performed += instance.OnTouchObjectB;
                @TouchObjectB.canceled += instance.OnTouchObjectB;
                @TouchObjectC.started += instance.OnTouchObjectC;
                @TouchObjectC.performed += instance.OnTouchObjectC;
                @TouchObjectC.canceled += instance.OnTouchObjectC;
            }
        }
    }
    public InGameActions @InGame => new InGameActions(this);
    public interface IInGameActions
    {
        void OnTouchObjectA(InputAction.CallbackContext context);
        void OnTouchObjectB(InputAction.CallbackContext context);
        void OnTouchObjectC(InputAction.CallbackContext context);
    }
}
